name = "face-analysis-worker"
main = "src/worker.js"
compatibility_date = "2024-03-26"

[[kv_namespaces]]
binding = "FACE_ADVICE_KV"
# Replace with your actual IDs from the Cloudflare dashboard
id = "ID_НА_ВАШИЯ_KV_NAMESPACE"
preview_id = "PREVIEW_ID_НА_ВАШИЯ_KV_NAMESPACE"

[[kv_namespaces]]
binding = "PRODUCTS_KV"
# Replace with your actual IDs for the products namespace
id = "ID_НА_PRODUCTS_NAMESPACE"
preview_id = "PREVIEW_ID_НА_PRODUCTS_NAMESPACE"
