import assert from 'node:assert/strict';
import { renderDashboardPage } from '../src/ui/dashboardPage.js';

export function testDashboardV2Page() {
  const html = renderDashboardPage('https://ai-visibility-edge.radilov-k.workers.dev');
  assert(html.includes('AI Visibility'));
  assert(html.includes('id="verdict"'));
  assert(html.includes('id="pillars"'));
  assert(html.includes('id="plan-week"'));
  assert(html.includes('/api/strategy/'));
  assert(html.includes('id="work-hub"'));
  assert(html.includes('action-bar'));
  assert(html.includes('Повторен анализ'));
  assert(html.includes('insights-panel'));
  assert(html.includes('blocker-banner'));
  assert(html.includes('btn-next-step'));
  assert(html.includes('btn-primary-action'));
  assert(html.includes('renderInsights'));
  assert(html.includes('edge-panel'));
  assert(html.includes('/api/edge/'));
  assert(html.includes('loadEdgeDecision'));
  assert(html.includes('activateEdge'));
  assert(html.includes('apiFetch'));
  assert(html.includes('site-stats'));
  assert(html.includes('cache-index-panel'));
  assert(html.includes('onboarding-panel'));
  assert(html.includes('drift-panel'));
  assert(html.includes('loadDriftStatus'));
  assert(html.includes('renderCacheIndex'));
  assert(html.includes('btn-reprocess'));
  assert(html.includes('loadSiteStats'));
  assert(html.includes('info-btn'));
  assert(html.includes('metric-modal'));
  assert(html.includes('findings-panel'));
  assert(html.includes('renderFindings'));
  assert(html.includes('finding-apply'));
  assert(html.includes('manual-workbench'));
  assert(html.includes('manual-task-list'));
  assert(html.includes('manual-save'));
  assert(html.includes('renderManualWorkbench'));
  assert(html.includes('Автоматични поправки'));
  assert(html.includes('renderRoadmap'));
  assert(html.includes('interpretMetricNow'));
  assert(html.includes('admin-token'));
  assert(html.includes('Gemini'));
  assert(html.includes('/api/advisor/chat'));
  assert(!html.includes('data-tab="workflow"'));
  assert(html.includes('operation-modal'));
  assert(html.includes('withOperation'));
  assert(html.includes('btn-export-manual'));
  assert(html.includes('manual-export'));
  assert(html.includes('exportManualRecommendations'));
}
